### PR TITLE
New SPDT switch footprint

### PR DESCRIPTION
**Pull request by mpkopec**
http://www.tme.eu/en/details/tsm102c3/przelaczniki-dzwigniowe/ninigi/

### CODE REVIEW

**Comment by michal777** [comment]
Line width of silkscreen line should be 0.15 mm - please replace "(width 0.1))" with "(width 0.15))" - (rule 6.5)
Pad 1 should be at 0, 0 (rule 6.3)
Courtyard should be added (rules 6.6, 6.7)
https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt#L70

**Comment by CarlPoirier** [comment]
Furthermore, this will go in Buttons_Switches_ThroughHole.pretty.

**Comment by mpkopec** [comment]
OK, I will correct the footprint and move it to the other repo. Thanks 
for your input guys! :)
W dniu 2015-02-23 o 14:23, CarlPoirier pisze:
> Furthermore, this will go in Buttons_Switches_ThroughHole.pretty.
>
> On Sun, Feb 22, 2015 at 5:52 AM, michal777 <notifications@github.com> 
> wrote:
>
> > Line width of silkscreen line should be 0.15 mm - please replace "(width
> > 0.1))" with "(width 0.15))" - (rule 6.5)
> > Pad 1 should be at 0, 0 (rule 6.3)
> > Courtyard should be added (rules 6.6, 6.7)
> >
> > 
> https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt#L70
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/KiCad/Discret.pretty/pull/4#issuecomment-75429743>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KiCad/Discret.pretty/pull/4#issuecomment-75539663>.
>

-- 

Z poważaniem,
Maciej Kopeć
maciejpkopec@gmail.com <mailto:maciejpkopec@gmail.com>

**Comment by SchrodingersGat** [comment]
Closing this

**Pull request closed without merging**
