### PR TITLE
add Leaded Varistor StandarD Series

### PR DESCRIPTION
**Pull request by andres53016**
I generate various footprint for varistor.

### CODE REVIEW

**Comment by andres53016** [comment]
Hi, here (https://github.com/andres53016/generator_siov) I write a python script to generate the footprints (144 footprints) from a table (siov_dimension.csv), the table I copy from www.epcos.com/inf/70/db/var_11/SIOV_Leaded_StandarD.pdf.

**Comment by michal777** [comment]
1. Don't add "  (at ..." in 2nd line. New verisions of KiCad don't do it.
2. Don't add "  (tags "")". "  (tags "varistor")" is better. If there are no tags don't add the line.
3. Newline character should be added at the end of file.
4. Unnecessary zeros in numbers should be cut.
5. Probably it should go to other library.
6. Please follow new recommendations about reference and value. Here is template (default empty footprint created by fresh build of KiCad):

(module zxcv (layer F.Cu) (tedit 54F7185A)
  (fp_text reference REF** (at 0 0.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value zxcv (at 0 -0.5) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
)

**Comment by andres53016** [comment]
Hi, thank's for the feedback, I applied the recommended changes.  And where I put the polyfuse footprints ? (100 footprints aprox).

**Comment by keruseykaryu** [comment]
I'm wondering. Your script create a 144 footprints for particular varistors. Most of them differs only in voltage clamp value. Why create single footprints for them?
We can just create one footprint per type: S05K, S07K, S10K... This way we will have only 10 new footprints in library which are suitable for whole serie.

> And where I put the polyfuse footprints ? (100 footprints aprox).

My doubts will also cover those footprints too.

**Comment by michal777** [comment]
I think it will be better to create footprints with dimensions in their names. Then the footprints will be more general and it will be easier to assign them for varistors from other manufacturers. Also duplicates will disappear.
And some things to improve:
(tags "varistor, SIOV") -> (tags "varistor SIOV")
VAR** -> REF**
(font (size 1 1)(thickness 0.15))) -> (font (size 1 1) (thickness 0.15)))

**Comment by keruseykaryu** [comment]
> I think it will be better to create footprints with dimensions in their names. Then the footprints will be more general and it will be easier to assign them for varistors from other manufacturers.

I support this idea.

**Comment by andres53016** [comment]
The Varistor have four important dimensions, in this case "a", "e", "w" and "th". I suggest  this dimension rounded to 0.25mm step (thus the amount of duplicates are reduced and maintains good accuracy) and the dimmensions in the footprint name.

Sorry for my english..

**Comment by andres53016** [comment]
@keruseykaryu 
if I only have in mind the width and height are 99 footprints.
if I round to 0.5 I get 39 differents footprints.
If I round to 1mm I get 25 differents footprints.
What should I do?

**Comment by keruseykaryu** [comment]
Create as less as possible. 
In my own footprint library I have only 5 footprints for SIOV, and this amount is suitable for all of varistors we have on our company warehouse.

**Comment by andres53016** [comment]
Thank's for feedback, It should be ok now.

**Comment by michal777** [comment]
I think we need Carl's opinion about creating new library. This library is too messy and probably should disappear in future. If new library will be created I think it's OK to fill it with even large number of varistors. It's hard to say which dimensions users will need so maybe it's better to make more.
Could you add courtyard with clearance 0.25 mm, rounded to 0.05 mm?
I don't understand the names. Which dimension are specified in names? I think that both x and y distances between pads should be in the names.

**Comment by andres53016** [comment]
The name is Varistor_Disc_(diameter) _RM(x distance between pads) .kicad_mod. The footprint created according to their diameter (5 group) .  The height is the highest in the Group. And the y distance between pads is the Group average, since these have an error of +-1mm. I have to traje english lessons :P.

**Comment by CarlPoirier** [comment]
Hi @andres53016,

For the naming, I recommend something like the disc capacitors from Capacitor_ThroughHole.pretty.

We ended up taking another direction than what was originally planned with the KLC, so I'll take this occasion to refine it. Sorry for the inconvenience.

Thanks!

**Comment by andres53016** [comment]
Hi @CarlPoirier 
the name would be as follows:
Varistor_Disc_10MM_RM7.5 -> Varistor_Disc_D12_W8_P7.5
is it right?

**Comment by CarlPoirier** [comment]
You could even shorten by replacing "Varistor" with its reference designator, "RV".

**Comment by michal777** [comment]
@CarlPoirier
What about new repository and number of these footprints? Should anything be put into this library?

**Comment by CarlPoirier** [comment]
I created a new repository called Varistors.pretty and pulled the stuff from this repo, so Pablo, you have the commits in your name.

**Pull request closed without merging**
